_wandb:
    value:
        cli_version: 0.25.0
        e:
            mwbrn83qot5ovgc719c6oofjoqradmoy:
                args:
                    - --file_url
                    - https://raw.githubusercontent.com/scikit-learn/scikit-learn/4dfdfb4e1bb3719628753a4ece995a1b2fa5312a/sklearn/datasets/data/iris.csv
                    - --artifact_name
                    - iris_dataset
                    - --artifact_type
                    - raw_data
                    - --artifact_description
                    - This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length
                codePath: src/iris_exercise/download_data.py
                codePathLocal: download_data.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "368236998656"
                        used: "58859782144"
                email: fabio_lima07@yahoo.com.br
                executable: /home/fabiolima/Desktop/MLOps/.venv/bin/python
                git:
                    commit: fe3083115343304eb2ca12d6c417df32dec88628
                    remote: https://github.com/FabioCLima/MLOps.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-dd5efa7f-b48f-0cdd-7215-9b3b34dfcc62
                host: Fabio
                memory:
                    total: "33252253696"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/fabiolima/Desktop/MLOps/src/iris_exercise/download_data.py
                python: CPython 3.13.12
                root: /home/fabiolima/Desktop/MLOps/src/iris_exercise
                startedAt: "2026-03-04T21:24:08.509229Z"
                writerId: mwbrn83qot5ovgc719c6oofjoqradmoy
        m: []
        python_version: 3.13.12
        t:
            "3":
                - 2
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
