_wandb:
    value:
        cli_version: 0.25.0
        e:
            gr5voeqf9mjv690st1unu6bf2jsskn1r:
                args:
                    - --input_artifact
                    - iris.csv:latest
                    - --artifact_name
                    - cleaned_data
                    - --artifact_type
                    - clean_data
                    - --artifact_description
                    - Iris dataset with t-SNE components added
                codePath: src/iris_exercise/process_data/process_data.py
                codePathLocal: process_data.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "368236998656"
                        used: "59457646592"
                email: fabio_lima07@yahoo.com.br
                executable: /home/fabiolima/Desktop/MLOps/.venv/bin/python
                git:
                    commit: fe3083115343304eb2ca12d6c417df32dec88628
                    remote: https://github.com/FabioCLima/MLOps.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-dd5efa7f-b48f-0cdd-7215-9b3b34dfcc62
                host: Fabio
                memory:
                    total: "33252253696"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/fabiolima/Desktop/MLOps/src/iris_exercise/process_data/process_data.py
                python: CPython 3.13.12
                root: /home/fabiolima/Desktop/MLOps/src/iris_exercise/process_data
                startedAt: "2026-03-05T13:42:33.835651Z"
                writerId: gr5voeqf9mjv690st1unu6bf2jsskn1r
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.13.12
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
